services:
  app:
    build: .
    environment:
      PORT: 8080
      DATABASE_URL: postgresql://neondb_owner:npg_dSN4MJKp2lkq@ep-floral-field-aeuxm9nl-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      CORS_ORIGIN: "*"
      PUBLIC_BASE_URL: https://english4sp.stinis.ddns.net
      UV_THREADPOOL_SIZE: 128
    ports:
      - "8080:8080"
